apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "4"
    creationTimestamp: "2024-07-03T15:29:41Z"
    generation: 5
    labels:
      app: hello-world
    name: hello-world
    namespace: default
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: hello-world
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: hello-world
      spec:
        containers:
        - image: in28min/hello-world-rest-api:0.0.2.RELEASE
          imagePullPolicy: IfNotPresent
          name: hello-world-rest-api
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
kind: List
metadata:
  resourceVersion: ""
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.231.34
  clusterIPs:
    - 34.118.231.34
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 31974
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello-world
  sessionAffinity: None
  type: LoadBalancer
